server:
  port: 9527

spring:
  application:
    name: cloud-gateway #以微服务注册进consul
  cloud:
    gateway:
#      动态路由配置
      discovery:
        locator:
          enabled: true # 开启根据服务发现的自动路由功能
          lower-case-service-id: true # 将服务名转为小写
  security:
    oauth2:
      resourceserver:
        jwt:
          # 配置授权服务器的JWK Set URI，网关将从这里获取公钥来验证JWT签名
          # cloud-auth运行在9123端口
          issuer-uri: http://localhost:9123 # cloud-auth的Issuer URI
          jwk-set-uri: http://localhost:9123/oauth2/jwks # cloud-auth的JWK Set端点



# knife4j:
#   # 聚合swagger文档
#   gateway:
#     enabled: true
#     # 排序规则(tag/operation排序自4.2.0版本新增)
#     # 取值：alpha-默认排序规则，官方swagger-ui默认实现,order-Knife4j提供的增强排序规则，开发者可扩展x-order，根据数值来自定义排序
#     tags-sorter: order
#     operations-sorter: order
# #指定根据服务列表获取api
#     strategy: discover

# discovery:
#     # 指定聚合的接口文档
#     discover:

#       version: openapi3
#       enabled: true
