package com.overthinker.cloud.common.core.utils.Iutils;

public interface IStringUtils {
    boolean isEmpty(String str);
    boolean isNotEmpty(String str);
    boolean isBlank(String str);
    boolean isNotBlank(String str);
    String trim(String str);
    String trimAll(String str);
    boolean equals(String str1, String str2);
    boolean equalsIgnoreCase(String str1, String str2);
    boolean startsWith(String str, String prefix);
    boolean endsWith(String str, String suffix);
    boolean contains(String str, String searchStr);
    int length(String str);
    String substring(String str, int start, int end);
    String substring(String str, int start);
    String replace(String str, String target, String replacement);
    String replaceAll(String str, String regex, String replacement);
    String[] split(String str, String separator);
    String toUpperCase(String str);
    String toLowerCase(String str);
    String reverse(String str);
    String repeat(String str, int count);
    String leftPad(String str, int length, char padChar);
    String rightPad(String str, int length, char padChar);
    String leftTrim(String str, String stripChars);
    String rightTrim(String str, String stripChars);
    int indexOf(String str, char searchChar);
    int indexOf(String str, String searchStr);
    int lastIndexOf(String str, char searchChar);
    int countMatches(String str, String sub);
    boolean isNumeric(String str);
    boolean isAlpha(String str);
    boolean isAlphanumeric(String str);
    String capitalize(String str);
    String uncapitalize(String str);
    String camelToUnderline(String str);
    String underlineToCamel(String str);
    String random(int length);
    String randomNumeric(int length);
    String toString(Object obj);
    String toString(Object obj, String defaultStr);
    String abbreviate(String str, int maxLength);
    String diff(String str1, String str2);
}