spring:
  application:
    name: cloud-ai
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3
          temperature: 0.4
      embedding:
        options:
          model: all-minilm

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true
        heartbeat:
          enabled: true

server:
  port: 8788

logging:
  level:
    org.springframework.ai: DEBUG