server:
  port: 8010
# ==========applicationName + druid-mysql8 driver===================
spring:
  application:
    name: cloud-Media-Asset-Processing-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:cloud}?currentSchema=minio
    username: ${DB_USER:root}
    password: ${DB_PASS:123456}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          enabled: false




## 连接 minio
minio:
  endpoint: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: cloud

# 媒体服务自定义配置
media:
  upload:
    max-file-size: 524288000 # 允许的最大文件大小 (500MB)
    allowed-content-types:
      - "image/jpeg"
      - "image/png"
      - "video/mp4"
    cleanup:
      enabled: true # 是否启用清理任务
      stale-threshold-hours: 24 # 任务过期阈值（小时）