spring:
  application:
    name: cloud-auth
  datasource:
    url: jdbc:postgresql://localhost:5432/springcloud2024_auth
    username: your_username # Please replace with your database username
    password: your_password # Please replace with your database password
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true # Enable retry mechanism
          initial-interval: 1000ms
          max-attempts: 3
    queue:
      audit-log: audit.log.queue # The queue to listen to
  security:
    jwt:
      key: 229a3b7a-f813-4e3a-8b7a-9b7e2d3f4c5a # This should be a strong, securely managed secret in a real environment
      expire: 24 # Expiration in hours

justauth:
  enabled: true
  gitee:
    client-id: YOUR_GITEE_CLIENT_ID
    client-secret: YOUR_GITEE_CLIENT_SECRET
    redirect-uri: http://localhost:8080/oauth/callback/gitee
  github:
    client-id: YOUR_GITHUB_CLIENT_ID
    client-secret: YOUR_GITHUB_CLIENT_SECRET
    redirect-uri: http://localhost:8080/oauth/callback/github
  wechat:
    client-id: YOUR_WECHAT_CLIENT_ID
    client-secret: YOUR_WECHAT_CLIENT_SECRET
    redirect-uri: http://localhost:8080/oauth/callback/wechat
