spring:
  application:
    name: cloud-ai
  ai:
    ollama:
      base-url: http://localhost:11434 # Your Ollama server address
      chat:
        model: llama3.1:8b # We are using Llama 3.1 8B model
        options:
          temperature: 0.7

#    vectorstore:
#      milvus:
#        client:
#          host: "localhost"
#          port: 19530
#          username: "root"
#          password: "milvus"
#        databaseName: "default"
#        collectionName: "vector_store"
#        embeddingDimension: 1536
#        indexType: IVF_FLAT
#        metricType: COSINE

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/mydatabase?cloud-ai
    username: root
    password: 123456

server:
  port: 8788